version: "3"
services:
  db:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    env_file:
      - ./common.env
  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - ./common.env
    ports:
      - 8081:8081
    depends_on:
      - db
  version: "3"
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./:/etc/nginx/conf.d
      - ./keys:/etc/nginx/keys
    ports:
      - "9999:9999"
  nodeapp:
    image: nbinik/healthapp
    restart: always
    env_file:
      - ./common.env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - nginx
